# Generated by Django 5.2.1 on 2025-06-09 13:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("preferences", models.JSONField(blank=True, null=True)),
                ("status", models.CharField(default="active", max_length=20)),
                ("subscription_date", models.DateTimeField(auto_now_add=True)),
                (
                    "unsubscribe_token",
                    models.UUIDField(blank=True, default=uuid.uuid4, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
