# Generated by Django 5.2.1 on 2025-07-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="authors/"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="name",
            field=models.CharField(default="writer", max_length=255),
        ),
    ]
