# Generated by Django 5.2.1 on 2025-07-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CryptoPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=20, unique=True)),
                ("price", models.DecimalField(decimal_places=8, max_digits=20)),
                ("percent_change", models.FloatField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("market_cap", models.BigIntegerField(blank=True, null=True)),
                ("circulating_supply", models.BigIntegerField(blank=True, null=True)),
                ("volume_24h", models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
